# Generated by Django 6.0.3 on 2026-03-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=10)),
                ('submission_type', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=10)),
                ('product_name', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
